-- Разовый импорт: позывные корреспондентов из личного лога R9OGL
-- (HAMLOG.ONLINE, экспорт R9OGL-02-Aug-2026-15-34.adi, 3209 QSO, 1422
-- уникальных позывных в логе). 1416 из них ниже — 6 отсеяны как мусор вида
-- "R9A-048": это SOTA/POTA-референсы, залогированные в поле CALL по ошибке,
-- не настоящие позывные, и содержат "-", которого нет в таблице Морзе.
--
-- INSERT ... SELECT ... WHERE NOT EXISTS вместо простого INSERT IGNORE:
-- в таблице callsigns НЕТ уникального индекса на callsign (см. schema.sql),
-- поэтому INSERT IGNORE тут не защитил бы от дублей между запусками —
-- сверяемся с уже существующими строками вручную. Безопасно выполнять
-- повторно: то, что уже есть в таблице, просто пропустится.
--
-- Разовый файл, как database/seed_callsigns.php — после применения можно
-- удалить.

INSERT INTO callsigns (callsign, country)
SELECT x.callsign, x.country FROM (
  SELECT 'R9UBP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RC4PG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9HU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN7JKB' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'R4FCS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA4HQO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9YAY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB9UZA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN7O' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R1IAM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA6FEH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA0DX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6DFI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3OA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6OBP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9SBH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R5ZK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4CGQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ6AQX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3TLB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA4WGS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ0W' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA0AMF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RO1A' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RY4FWE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3GPM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW3KU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RC4H' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9SRT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2RAM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R100KPB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4SC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R7BO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6HA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA0AY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4FHO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK9DM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4AFM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ0SW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN7FHA' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'UB6O' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RJ6OU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ0SH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0CC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0IAI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA0IHY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9WEI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4FBH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6LDW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R1NA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UK8LX' AS callsign, 'Узбекистан' AS country
  UNION ALL SELECT 'UB9HAM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV6AKC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV6YT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU0ANX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0AKB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB9UZC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW9FM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW6FS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3D' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UK8OCU' AS callsign, 'Узбекистан' AS country
  UNION ALL SELECT 'RU4PIC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2RZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'DL1DXX' AS callsign, 'Германия' AS country
  UNION ALL SELECT 'R3TLW/4' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK6AHE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN6DZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA0R' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BG0FAN' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'RG0S' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW4HM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4CA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9OFG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JM6EBR' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'JA4MMO' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'JA3KVT' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'JL1GYZ' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'UA4PT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JR6IQI' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'R0SDO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA0SCA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX9ABI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JA7FLI' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'RX3ASQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8CGO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JF2HPA' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'R8CEG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JA2HYD' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'JA3SIA' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'UA0TP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BD4UN' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'R8OAE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9OBJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ1O' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'T30TTT' AS callsign, 'Кирибати' AS country
  UNION ALL SELECT 'BG2GNR' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'BG2ATH' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'UA9LLE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RM9WU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB9OES' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9OGJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8OAL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RD9UG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA0WDJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA0ACZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RC0AB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RG8U' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK9JD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'EU1FQ' AS callsign, 'Беларусь' AS country
  UNION ALL SELECT 'UA9UFG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BD0AH' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'R9UCI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK4FD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA0LQE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ6CO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4FEQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RD3AD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'FR8TZ' AS callsign, 'Реюньон' AS country
  UNION ALL SELECT 'R7DX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4CGX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA0CGN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3APK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3Y' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW0LO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3VA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9SCJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4CBN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R1QD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA0SR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4CX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA6J' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9AJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JA1VSL' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'R7DP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4UIV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3FH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3GJM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4RN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU4I' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9FF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RC0CD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4ALY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0CAF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA0LHS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BG6NLE' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'R0AHR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UK8GM' AS callsign, 'Узбекистан' AS country
  UNION ALL SELECT 'UA0LDW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA6ARR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JA9KKD' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'R9IG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK8W' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA4PBT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA4FEN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2ET/9' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4HJN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'OZ1HPS' AS callsign, 'Дания' AS country
  UNION ALL SELECT 'RA4Y' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA4PEF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4CAA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UK8FCM' AS callsign, 'Узбекистан' AS country
  UNION ALL SELECT 'BA5AN' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'JK1GKG' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'RW9AD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8AIJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BG2DIH' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'RA6WF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU0ANR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB0AKR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX9O' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB9YBB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4UAI/9' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2RAN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9FOO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB4CMD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9FLW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB4WAT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6DR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9OGG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9UDD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0TA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA0AMF/P' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX9UCF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA0LSG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RJ0A' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA8Y' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ0OFW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN7PIN' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'R2EC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9TS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8CAM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3TRR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9KBC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA0JBY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK2Z' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9ODK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RG3M' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4PIS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R1BC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RM9WF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9CMO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK6AH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU6K' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK4UZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU4SS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9299SWL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU3QR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB8A' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU5X' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU6L' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UD8S' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9AMO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UK8GL' AS callsign, 'Узбекистан' AS country
  UNION ALL SELECT 'UN7PFG' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'RG5A' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9APA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BA6KC' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'R6DBT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN7PME' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'RW0IM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN7IN' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'UA0ACG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0SDM/P' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW4W' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN7RM' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'UN7ZAG' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'R9OFA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9FK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ3EW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0UAQ/M' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9CUU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA4HJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8LCX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN7EAX' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'R8KAN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9CAD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9FLI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA6EKC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9UHW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU0AJC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB9UZD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0AEW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4YAQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4UCQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA4UDB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4UVL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW9WK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ3A' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RC8SA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV4LD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RY9W' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN7CFG' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'UN7FBW' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'UA9LT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6LI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6GZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9OX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2ANQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB3DYA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9FE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9FFJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R7ME' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UK8CB' AS callsign, 'Узбекистан' AS country
  UNION ALL SELECT 'UN7MBN' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'UA9JTJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9SY/4' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'I1RJP' AS callsign, 'Италия' AS country
  UNION ALL SELECT 'UN9LCW' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'UA9CK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UI0A' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN4PG' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'YO6LM' AS callsign, 'Румыния' AS country
  UNION ALL SELECT 'RY7F' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9CR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'YO4NF' AS callsign, 'Румыния' AS country
  UNION ALL SELECT 'RU0ALC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB0AZM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN7NCG' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'R8CBR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0ABK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN7JGI' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'RQ4F' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9CQV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8LCA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU9CK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9OBN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9ON' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ6AKF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6OEM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA0WDQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0WB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN7BB' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'RY9YAD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN7LBU' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'UA9LAO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9HEE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8LB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'SV2AEL' AS callsign, 'Греция' AS country
  UNION ALL SELECT 'RL3T' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA1QD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'SP4TKA' AS callsign, 'Польша' AS country
  UNION ALL SELECT 'R9BT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW4HBD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3ON' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9AX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4FET' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9JM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA6JQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV9CX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3VX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6DYK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4FW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3RGQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV6MX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RD3DM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA0ZIH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4ADD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6HB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX0TX/P' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB0SNX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R1943OD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3PBK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9FEM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9SBQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UD6B' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA0LMO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9CP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3ZFB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2SCO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RC0JD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW6MJL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3PMP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA6PKZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RC0UC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9AAB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3ZDC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UF1I' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9HBH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9HEH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN7CAN' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'UB9MBJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN7NQ' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'EX8VI' AS callsign, 'Киргизия' AS country
  UNION ALL SELECT 'RO6G' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ9O' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU9MR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW9MZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9YIS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0AHU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0ACF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9UH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0AJE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9UCZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB0ADB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ6L' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9DZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'SM4IED' AS callsign, 'Швеция' AS country
  UNION ALL SELECT 'RA6LO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU9AD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9AL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BG0EOQ' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'RC7O' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN0JT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6TA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX6LG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN7PTN' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'R6LOM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4HG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9DZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3LBK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RD7P' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3GT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9WCK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3SAQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3RDN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA6MQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX6ACJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RC6OG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RC7KJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'US1EA' AS callsign, 'Украина' AS country
  UNION ALL SELECT 'RU7C' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ7B' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV9OW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6DCE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV9U' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9MBG/P' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9MX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BG8GAM' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'RN3OX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UI6A' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX3DQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN7LEW' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'UA0AV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2HM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9AAA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6TY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN6LBT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB3WCY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2WAF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9UIS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW3DW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA4HDB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA2FF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU3DNN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3FO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW2Z' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV0AR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BG0ETY' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'RK4FAJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN3QEV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA6LGP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9HDM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9OJA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6LCS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RO8W' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB4FTI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9AC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA6ABE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RD3MJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB3YFP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3SS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA6HKG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3LBF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8AHM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8CT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9UG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BG4OXQ' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'UA6WFO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ6AUK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RD3ZG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4QB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6JBM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3TMV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ3EK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK6ANZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU6HQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV9CSF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6DXX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW3TM/MM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'GW0KBO' AS callsign, 'Уэльс' AS country
  UNION ALL SELECT 'RU6UR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN6LDQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R50NUR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RJ7C' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RY7B' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'DL1DGS' AS callsign, 'Германия' AS country
  UNION ALL SELECT 'RN6C' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0SK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3POG' AS callsign, 'Россия' AS country
  UNION ALL SELECT '4L7T' AS callsign, 'Грузия' AS country
  UNION ALL SELECT 'US8KA' AS callsign, 'Украина' AS country
  UNION ALL SELECT 'OH3BRJ' AS callsign, 'Финляндия' AS country
  UNION ALL SELECT 'RZ6ASO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3LCG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'DL3MIB' AS callsign, 'Германия' AS country
  UNION ALL SELECT 'RA3ZGT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RO2Z' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9ANC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8AU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3PK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK1AF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RQ9O' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'HA3MN' AS callsign, 'Венгрия' AS country
  UNION ALL SELECT 'UA3RBM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9CS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV0APH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN7LAX' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'R3GI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9SY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA8CP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3BV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RI0SP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA6OV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9QGS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R5GG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9WGG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB9YAI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4RR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0OM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU9CZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9CUA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8KBL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R5VAN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK9DO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN6LPI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RC6AI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8CCI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6UBM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4IK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW9SE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX0SA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R7EH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4PCA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RT1I' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN7NBB' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'UB8JDJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9MBK/P' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB9MBT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RL9M/P' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9YDH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9HBI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9MDL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9YER' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9UAO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0ACR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX9YM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK0STK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UD8A' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9JKB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9CDC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R5AV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3KED' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA1ZFL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R1CBH/P' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RT3S' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3EDX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3SV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW3VA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4P' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA1QY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0RI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4HBS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2BCT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3TIT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA4LLO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UC3UAA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3DOA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RT9K/P' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RD4HX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3MD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA1IA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'LB8OH' AS callsign, 'Норвегия' AS country
  UNION ALL SELECT 'JN1ILK' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'RA8CP/M' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB6O/M' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9SQK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN4AZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UK8FKK' AS callsign, 'Узбекистан' AS country
  UNION ALL SELECT 'UN7RM/P' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'UA3SNB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW9WJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9YM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9MKA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8OAK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0UAR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU0ANU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX0WX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9VM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9UBE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9UFX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9HBN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB9UAQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4CGI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB4CJJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3ZBI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RG2E' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB3RGM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4CN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4CJB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9YDE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9YER' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9YNY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9OOD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9YJE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8YR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9DV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA6JCM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3RNQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6GX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6FCU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9CUS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4NAL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6QAA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK6FO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW4PIC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UD6AVY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RD6B' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ6HSF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R500X' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RD9SAE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R500SMP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RT6DE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9OAU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN8JKZ' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'RA9YTS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9UER' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN2H' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3685SWL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9FF/P' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BH8BMZ' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'R4RL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JR3WYM' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'JA1VGV' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'RA3AV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RT9OM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3ZCQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UD0O' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BI3OGV' AS callsign, 'Китай' AS country
  UNION ALL SELECT '7N1PVD' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'RA9FEU/M' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX4D' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV3OG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0ABC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA0SX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV9OA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9CUP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB9HEU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9FFZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UG0B' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8CGE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW7B' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JR1KMO' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'R6LFO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2ZO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'DS4FZX' AS callsign, 'Южная Корея' AS country
  UNION ALL SELECT 'R1BLH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3DJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RG4D' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN1CW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB0SCV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R7IM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JS1TSS' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'RL3K' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB1AKX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R1CF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JF1VAE' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'UA3IHJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2FC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0LIE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW3LD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0SDM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4HHP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RL6MT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JM1SZY' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'BD6JN' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'JA1NGD' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'RA9ATY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9BL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW0AE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JH5GEN' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'JG5VFK' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'RJ1O' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RG3H' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R5FQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3KKG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JH7MKB' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'UA0JCG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA0SCZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BI6PKB' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'JG0EXP' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'RD0B' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0JAC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9ZO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA8U' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0SDV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BA4IE' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'R9OEJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4LAG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4ZZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9HM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RC9YG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9OAE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW9ULK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RQ1A' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV3PK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA5BC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4CKE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4CGS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB8CQB/P' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN8CG' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'R9UHD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4PNZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA6BNR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BG0HP' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'R9FZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0ABX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9UHA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9OIY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3RPW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA0ADX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN8BK' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'R0SAP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN9PQ' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'R8LCM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU3KD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RC9C' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9OF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4RC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0WW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0WAB/P' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0WBQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0SDL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9HEA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9UAU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0AJS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0AGH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3BY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA0CCK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UD6AMF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB8F' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB0ALL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0SCI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB9UTA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV9USA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8UE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9HAF/M' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA4NCX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JR1KPW' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'UA6ANQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4M' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK9CW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UR5MQX' AS callsign, 'Украина' AS country
  UNION ALL SELECT 'RN4HJG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8CCC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9MQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX9CET' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RF9C' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BA4OO' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'UA0SGY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JA7WLY' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'RN3QTS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0DZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JH2BJL' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'JR9NEE' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'R3DBN/P' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW3DU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3SMZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4YC/M' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA1OJL/M' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK7N' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9ZCC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ0WS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4CPA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9ME' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4FCK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JG3LGD' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'RA3AHN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4IQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BG4IAJ' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'R4FS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA6FBO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK4FH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2SCL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3LNM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4LA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA6BW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK4CH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'OH1LA' AS callsign, 'Финляндия' AS country
  UNION ALL SELECT 'JA2INL' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'JR3UIC' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'RU4PH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'OK1WCF' AS callsign, 'Чехия' AS country
  UNION ALL SELECT 'JG1GEO' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'RZ3DZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV6F' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4PU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8AAU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'SP7JY' AS callsign, 'Польша' AS country
  UNION ALL SELECT 'R9SEY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX9WM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX4SA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA4LDP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'DK3HV' AS callsign, 'Германия' AS country
  UNION ALL SELECT 'PI4TX' AS callsign, 'Нидерланды' AS country
  UNION ALL SELECT 'BH3MPM' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'BA8DK' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'RC6AA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'II2IARU' AS callsign, 'Италия' AS country
  UNION ALL SELECT 'RU0S' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BV7RR' AS callsign, 'Тайвань' AS country
  UNION ALL SELECT 'JA3JFT' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'JA3XPO/3' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'UA0SM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JH1GJY' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'R8CHY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BH8FSI' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'RZ4FWA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4FV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9V' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8LCM/P' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK0S' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'SP6M' AS callsign, 'Польша' AS country
  UNION ALL SELECT 'RU0AHO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2EA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4DB/8' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK4PR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BH6LIG' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'SM6/DL1HTW' AS callsign, 'Швеция' AS country
  UNION ALL SELECT 'RV9CME' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8CIR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3GDJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9UDK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8CGZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW4PAN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3NFG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ4AT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB6OAJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JA9LX' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'RZ4AZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9DJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'VU2LMO' AS callsign, 'Индия' AS country
  UNION ALL SELECT 'BH8UKJ' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'R0AH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV9ABE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ9A' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UI8A' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3PFR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8AGK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU4C' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW3DBX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9WNA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6FFB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN9CA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3TKM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX3AEX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4WBU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3XBS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2AEP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN3YN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3RDY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'GM4WJA' AS callsign, 'Шотландия' AS country
  UNION ALL SELECT 'DF1SD' AS callsign, 'Германия' AS country
  UNION ALL SELECT 'EA5ET' AS callsign, 'Испания' AS country
  UNION ALL SELECT 'G0ABI' AS callsign, 'Англия' AS country
  UNION ALL SELECT 'PD0HLA' AS callsign, 'Нидерланды' AS country
  UNION ALL SELECT 'DF8RU' AS callsign, 'Германия' AS country
  UNION ALL SELECT 'PA3APH' AS callsign, 'Нидерланды' AS country
  UNION ALL SELECT 'OH6IH' AS callsign, 'Финляндия' AS country
  UNION ALL SELECT 'BA7SAY' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'BI6NYO' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'RW9CC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB6OCP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN7PNF' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'R8CCF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9UAE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0WBK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RC2W' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R5ZQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3RQS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9MPV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9MAW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV9MU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK3BX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA4FKT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV9CT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JE4VSC' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'UA4PQF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3PKX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3ECD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R5ZT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB4CDL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'YO4NT' AS callsign, 'Румыния' AS country
  UNION ALL SELECT 'ON7GB' AS callsign, 'Бельгия' AS country
  UNION ALL SELECT 'BG7SFE' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'JH5HDA' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'RV9WJP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB8COS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA8JE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BH3HAO' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'R9XAC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'PD1ADA' AS callsign, 'Нидерланды' AS country
  UNION ALL SELECT 'PD7CA' AS callsign, 'Нидерланды' AS country
  UNION ALL SELECT 'PD7RF' AS callsign, 'Нидерланды' AS country
  UNION ALL SELECT 'UA9UPK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3CL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8ACF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BG3NBD' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'RG8G' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JH7GZW' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'R1OB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA1QGN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BY1RX' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'YU1UN' AS callsign, 'Сербия' AS country
  UNION ALL SELECT 'UA9CES' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA0WBR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9UFL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R5RC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4RF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV9UP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN7ZW' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'UN7NAG' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'UN7NAL' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'R026NY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2026L' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4PHH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4RAK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9LLB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN3ZDU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9LJD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4LCJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN7ICZ' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'UA3GLX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UD7K' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK4PL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R7BW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB3TAG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9AOY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9FEO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW3GF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4HHK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6DCK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA4WJT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R7BE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3LCK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9SAS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4CJN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN3QEI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2EAW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8XT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB1WCC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6LEF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3EH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3SAB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX3E' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3MPH/M' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK1N' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6LZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6DNF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8AII' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4CGR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4CGF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4LBL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R7EB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9SIV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6YCF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8CGY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'YL2SWY' AS callsign, 'Латвия' AS country
  UNION ALL SELECT 'R3RBK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'ES4ACA' AS callsign, 'Эстония' AS country
  UNION ALL SELECT 'R4HHQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2RDD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN7AS' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'R4UAX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4CHS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6ZHQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9CVQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3TAZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4PCE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2RAK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9ARC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN6DC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9CAE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9JR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9CQX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ3DEV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9XSL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RG3Z' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RT3H' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN7C' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9CVQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA1D' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RO7B' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ3PP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4HKQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4CHQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN7RBX' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'R3KCL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3QTH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8AC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4HGO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3RKG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB6LXE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB6ZBD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4CBD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4NCA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4PIN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9OM/6' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6WD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX3QFI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW6HTI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB5X' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9FO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RL2G' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4PJE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3TRQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'ES4EA' AS callsign, 'Эстония' AS country
  UNION ALL SELECT 'RZ9WY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RM6LA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RD6ZT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9FAI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3KPI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8CCH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RL6ZM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA6OB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R7OT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3KKK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV3KN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN6HBI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RC6OS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV6HHO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9SEO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9SBW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9SVV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6JBO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX6M' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK4CL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3PET' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6FHF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX9PCT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'US8ILQ' AS callsign, 'Украина' AS country
  UNION ALL SELECT 'RN9ASA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB9MBE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6ZAS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4ABM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3RBD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4FT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN6CK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'EU6PM' AS callsign, 'Беларусь' AS country
  UNION ALL SELECT 'UB6OBD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'EW1MM' AS callsign, 'Беларусь' AS country
  UNION ALL SELECT 'RA9MEM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV9AOR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9SQQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RO9U' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN3RGV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV7G' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN9AVE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R7TG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4CCV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6DKC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R5VDZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3WII' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3DCT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU3KP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX3QAO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK6BU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'SN31ROT' AS callsign, 'Польша' AS country
  UNION ALL SELECT 'R5KB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN6ACO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R5DF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA4CBX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6JA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK6OL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RM5W' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3BU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6ZHA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN6LR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9TX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3GIE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU3FP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R1QAI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN6LPC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4RO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA6BJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA6BLX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2ZGN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'F5FCH' AS callsign, 'Франция' AS country
  UNION ALL SELECT 'RX3KG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK6BP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB4FAN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RM1O' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX6DK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB3RHI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3RRD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9FCG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8FE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3TLR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3RCW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3AIR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4UAA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3RMU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'IZ3NYG' AS callsign, 'Италия' AS country
  UNION ALL SELECT 'R8CW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2UZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4GM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3PMM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'S55BA' AS callsign, 'Словения' AS country
  UNION ALL SELECT 'DL4DXF' AS callsign, 'Германия' AS country
  UNION ALL SELECT 'RC6AD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'EK6LAG' AS callsign, 'Армения' AS country
  UNION ALL SELECT 'RA6CR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ6HLK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA6YGP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK3OR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R1KP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'DG0OME' AS callsign, 'Германия' AS country
  UNION ALL SELECT 'LZ4VR' AS callsign, 'Болгария' AS country
  UNION ALL SELECT 'IC8TEM' AS callsign, 'Италия' AS country
  UNION ALL SELECT 'S51UN' AS callsign, 'Словения' AS country
  UNION ALL SELECT 'F8GDP' AS callsign, 'Франция' AS country
  UNION ALL SELECT 'RA6ZC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV6ARZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3WY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'S51CK' AS callsign, 'Словения' AS country
  UNION ALL SELECT 'IR0IDP' AS callsign, 'Италия' AS country
  UNION ALL SELECT 'UR2MX' AS callsign, 'Украина' AS country
  UNION ALL SELECT 'R4HCN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW6FT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9LAJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4PDX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RL6OV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RM8G' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN8LWZ' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'R1BDX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'S52D' AS callsign, 'Словения' AS country
  UNION ALL SELECT 'RA6HN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4FDP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB3DYU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RL7Z' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2GBR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'IK4LZH' AS callsign, 'Италия' AS country
  UNION ALL SELECT 'R2ZC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA1ALW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3UHP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA6LLP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4HU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RD3ZI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB4CCP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV3DED' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RQ3F' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW3QEG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6LKR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4RY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA6LSX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4HIZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4HTT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9SJG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6PAT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RD4AC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3RAV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4PBA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3PNL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW3QBM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9SAF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA0TAB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA4CFM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3QEQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3QZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX6LVC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9AE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4CGX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2GDQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN3QVE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK4FV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA4HNU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RM1C' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R5QA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3IMS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU7N' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3PTC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB0AKS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA6BOB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4SGX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4FDC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2LM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV6HAF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'DD7EE' AS callsign, 'Германия' AS country
  UNION ALL SELECT 'DL6ZOG' AS callsign, 'Германия' AS country
  UNION ALL SELECT 'UB6OFG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'F4GTB' AS callsign, 'Франция' AS country
  UNION ALL SELECT 'IZ0AEZ' AS callsign, 'Италия' AS country
  UNION ALL SELECT '9A4ZM' AS callsign, 'Хорватия' AS country
  UNION ALL SELECT 'SP2EWQ' AS callsign, 'Польша' AS country
  UNION ALL SELECT 'RN6MA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'PA2RO' AS callsign, 'Нидерланды' AS country
  UNION ALL SELECT 'BA6IM' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'RX6ART' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'EW8DU' AS callsign, 'Беларусь' AS country
  UNION ALL SELECT 'DL2TM' AS callsign, 'Германия' AS country
  UNION ALL SELECT 'R6OI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6KP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'OK2MI' AS callsign, 'Чехия' AS country
  UNION ALL SELECT 'R4DS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9WUY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ9AWA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0AAP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW6YT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA6OY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RG4H' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'YO6OGJ' AS callsign, 'Румыния' AS country
  UNION ALL SELECT 'R3PJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3KEO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4ART' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA4UCV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4PZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4PAX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4PGV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4PBM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN3QTA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW3QEP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RV6AAF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ7C' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA4CNX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3QPF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3OB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3YT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2DYI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB8AIF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB8AAF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA6WL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW6ADP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3DBS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R50KAMA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4RJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4CQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX3QAL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'F9CHM' AS callsign, 'Франция' AS country
  UNION ALL SELECT 'R4CKG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2014RK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2RAR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3OD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3KBV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4HBO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA6ALG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN3ZDR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6FHJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2ZEX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ6C' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA1ZGA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UD6ATF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3YCI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3WDV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'ES2ROL' AS callsign, 'Эстония' AS country
  UNION ALL SELECT 'RN3RGO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB6OCU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RK3IT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3RCF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6DBE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'S59WW' AS callsign, 'Словения' AS country
  UNION ALL SELECT 'R6FDU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'V6PA' AS callsign, 'Микронезия' AS country
  UNION ALL SELECT 'RV6APS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'YO3YX' AS callsign, 'Румыния' AS country
  UNION ALL SELECT 'DL1RBR' AS callsign, 'Германия' AS country
  UNION ALL SELECT 'UB9UXB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8LBR' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R7OX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RC9YI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA6ADQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3DAD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB6HJE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6LBT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3KEF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6LBC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3EAX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3HW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R5QL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9SAU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX3F' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6LNI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'DL5ZH' AS callsign, 'Германия' AS country
  UNION ALL SELECT 'RX6BV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'OB9OLM' AS callsign, 'Перу' AS country
  UNION ALL SELECT 'ON6WDL' AS callsign, 'Бельгия' AS country
  UNION ALL SELECT 'RK6ZL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6LJZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3RMG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8CCL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RD6ZY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6ZAH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2RFG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RD6OW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA4CMJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2GAL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB4RGQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA1T' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4FCT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2AKN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9FGJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4PCZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UR7IVD' AS callsign, 'Украина' AS country
  UNION ALL SELECT 'R6FEI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU6FE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6OJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UN0OA' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'RX3QFJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN3ZPZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2AIC/QRP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3PJS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3BBJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2DUQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA1AKU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB3RGJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R1BQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA4PKF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA6T' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6DLS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB3KGA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RC1TC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RD5T' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RL3QI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R4PF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6BP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RD6OJ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3OU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6DY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6OCB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RN3ATP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2DUI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3RS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'DJ1TU' AS callsign, 'Германия' AS country
  UNION ALL SELECT 'R4FDK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'ON8BB' AS callsign, 'Бельгия' AS country
  UNION ALL SELECT 'OM3CND' AS callsign, 'Словакия' AS country
  UNION ALL SELECT 'JT1CO' AS callsign, 'Монголия' AS country
  UNION ALL SELECT 'R3RP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9MP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R2HEU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9HAG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9UIK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU4B' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'SM3ULU' AS callsign, 'Швеция' AS country
  UNION ALL SELECT 'JE2UFF' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'UA3FO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R1NO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JN1XAI' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'SM3NRY' AS callsign, 'Швеция' AS country
  UNION ALL SELECT 'JK1WVC' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'JR2IMJ' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'SP3CUG' AS callsign, 'Польша' AS country
  UNION ALL SELECT 'R2DX/3' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JS1IFK' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'RZ6LY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9OTW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JP3HIW' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'RA4FUT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RY7G' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA3PAB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R7OQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA4ATB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BH3FZG' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'JL1IOC' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'JE3GUG' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'JQ3DUE' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'JH8KUQ' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'JA6SQR' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'RX0XWX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9UNA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU9YA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UP60L' AS callsign, 'Казахстан' AS country
  UNION ALL SELECT 'RP81MG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RP81TG' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RP81VF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RP81KE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RP81BA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'B1CRA' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'R4HDE' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU3GC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB9JBO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RP81PW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'DS4FWI' AS callsign, 'Южная Корея' AS country
  UNION ALL SELECT 'R9HEC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RP81BPZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9OTX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA0WBI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA0WHT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9UO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9FDM' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RP81PFP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UK8GBU' AS callsign, 'Узбекистан' AS country
  UNION ALL SELECT 'R9HEU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UE6RU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3RJY' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU0AJQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0ADO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA0ALB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA0WF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'IQ4JO' AS callsign, 'Италия' AS country
  UNION ALL SELECT 'UG4Y' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RD3MF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'EX8ABQ' AS callsign, 'Киргизия' AS country
  UNION ALL SELECT 'IR9RCAM' AS callsign, 'Италия' AS country
  UNION ALL SELECT 'RA3GJT' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9JLP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R8KBH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9HDU' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9JKM/M' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RX0W' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU0SC' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA9HFO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB4RGA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU0ANU/QRP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB9OEZ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA0WCV' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9UIO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU0SN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9HAL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA4PKX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3RDX' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R3KFI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA4CDW' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW3U' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA3ZBF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UB8FDO/9/P' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R50AVS' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9MP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0AGK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'JA7FVA' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'RA0LQ' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ9OL' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RW4HD' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA0FF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9JX' AS callsign, 'Россия' AS country
  UNION ALL SELECT '3B8HK' AS callsign, 'Маврикий' AS country
  UNION ALL SELECT 'RM3TO' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BG9VZ' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'RT25HK' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RU0AON' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RA9SCB' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RD0L' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RD0B/P' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'E70SZ' AS callsign, 'Босния и Герцеговина' AS country
  UNION ALL SELECT 'R7CA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R6DOP' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RL8C' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BA8BLK' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'JJ2CJB' AS callsign, 'Япония' AS country
  UNION ALL SELECT 'BG2EFX' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'RA9YTI' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R9ZAH' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RZ9UF' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'UA4CKN' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'BG5CZW' AS callsign, 'Китай' AS country
  UNION ALL SELECT 'RW0QA' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'RD0A' AS callsign, 'Россия' AS country
  UNION ALL SELECT 'R0SV/P' AS callsign, 'Россия' AS country
) AS x
WHERE NOT EXISTS (SELECT 1 FROM callsigns c WHERE c.callsign = x.callsign);
